const COLORS = {
    ORANGE: '#ED8E21',
    ORANGE_DARK: '#B57122',
    BLUE_SOFT: '#2491BF',
    BLUE: '#57CDFF',
    BLUE_DARK: '#052533',
}

module.exports = {
    theme: {
        textColor: {
            'rc-orange': COLORS.ORANGE,
            'rc-orange-dark': COLORS.ORANGE_DARK,
            'rc-blue-soft': COLORS.BLUE_SOFT,
            'rc-blue': COLORS.BLUE,
            'rc-blue-dark': COLORS.BLUE_DARK,
        },
        backgroundColor: {
            'rc-orange': COLORS.ORANGE,
            'rc-orange-dark': COLORS.ORANGE_DARK,
            'rc-blue-soft': COLORS.BLUE_SOFT,
            'rc-blue': COLORS.BLUE,
            'rc-blue-dark': COLORS.BLUE_DARK,
        },
        borderColor: {
            'rc-orange': COLORS.ORANGE,
            'rc-orange-dark': COLORS.ORANGE_DARK,
            'rc-blue-soft': COLORS.BLUE_SOFT,
            'rc-blue': COLORS.BLUE,
            'rc-blue-dark': COLORS.BLUE_DARK,
        },
        boxShadow: {
            'left': '-4px 0 4px -4px rgba(0, 0, 0, .25)',
            'top': '0 -4px 4px -4px rgba(0, 0, 0, .25)',
            'right': '4px 0 4px -4px rgba(0, 0, 0, .25)',
            'bottom': '0px 4px 4px rgba(0, 0, 0, 0.25)'
        },
        zIndex: {
            'inf': '2147483647',
            'neg': '-1',
            '100': '100',
            '200': '200'
        },
        spacing: {
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            '7/25': '28%',
            '48/50': '96%',
        },
        fontSize: {
            'xs': '.75rem',
            'sm': '.875rem',
            'tiny': '.875rem',
            'base': '1rem',
            'lg': '1.125rem',
            'xl': '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
            '8xl': '6rem',
            '9xl': '7rem',
            '10xl': '8rem',
            '11xl': '9rem',
        },
        width: {
            '28': '7rem',
            '36': '9rem',
            '80': '20rem',
            '96': '24rem',
            '020': '20%',
            '030': '30%'
        },
        height: {
            '020': '20%',
            '030': '30%',
            '050': '50%',
            'header': '11.25rem',
            '2header': '22.50rem',
        },
        fontFamily: {
            "Righteous": ['Righteous'],
        },
        extend: {},
    },
    variants: {
        backgroundColor: [ 'responsive', 'hover', 'focus', 'active', 'group-hover' ],
        height: [ 'responsive', 'hover', 'focus' ],
        textTransform: [ 'responsive', 'hover', 'focus' ],
        fontSize: [ 'responsive', 'hover', 'focus' ],
        alignItems: [ 'responsive', 'hover', 'focus' ],
        justifyContent: [ 'responsive', 'hover', 'focus' ],
        borderColor: [ 'responsive', 'hover', 'focus', 'focus-within' ],
        borderStyle: [ 'responsive', 'hover', 'focus' ],
        borderWidth: [ 'responsive', 'hover', 'focus' ],
        spacing: [ 'responsive', 'hover', 'focus', 'focus-within' ],
        outline: [ 'focus', 'responsive', 'hover' ],
        zIndex: [ 'responsive', 'hover', 'focus', 'focus-within' ],
        boxShadow: [ 'responsive', 'hover', 'focus', 'active', 'group-hover' ],
        textColor: [ 'responsive', 'hover', 'focus', 'active', 'group-hover' ],
        inset: ['responsive', 'hover', 'focus'],
        fontFamily: ['responsive', 'hover', 'focus'],
        boxShadow: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    },
    plugins: []
}
